const contenido = [
    {
    id: 1,
    titulo: 'Lección 1 — Introducción a Salud y Seguridad en el Trabajo (SST) y su relación con los planes de emergencia',
    objetivo: 'Objetivo: Entender la importancia de la SST y cómo los planes de emergencia forman parte de ella.',
    introduccion: 'La Seguridad y Salud en el Trabajo (SST) busca proteger la integridad física y mental de los trabajadores en el desarrollo de sus labores. No se trata únicamente de cumplir con normas legales, sino de crear un entorno seguro que minimice los riesgos de accidente y enfermedad. Dentro de este marco, los planes de emergencia son una herramienta clave, ya que permiten anticipar, preparar y responder de manera organizada ante eventos que puedan poner en riesgo a las personas, las instalaciones o la continuidad de las operaciones.',
    tituloA: 'Definición y normativa básica de SST.',
    definicionA: 'La Seguridad y Salud en el Trabajo (SST) es el conjunto de actividades orientadas a prevenir accidentes y enfermedades laborales, garantizando un entorno de trabajo seguro. En Colombia, la Ley 1562 de 2012 y la Resolución 0312 de 2019 establecen lineamientos que todas las empresas deben cumplir. Estos marcos normativos exigen la implementación de sistemas de gestión que integren la prevención y respuesta ante emergencias.',
    imagenA: 'https://i.pinimg.com/564x/a9/fd/c4/a9fdc45ce1b7f168338fb8c658908597.jpg',
    tituloB: 'Relación entre SST y planes de emergencia',
    definicionB: 'Los planes de emergencia forman parte del Sistema de Gestión en SST, ya que permiten responder a situaciones que, de no ser controladas, ponen en riesgo a las personas y a la operación de la empresa. Sin ellos, la prevención queda incompleta, pues se ignora cómo actuar en caso de que la amenaza se materialice.',
    imagenB: 'https://sp-ao.shortpixel.ai/client/to_webp%2Cq_glossy%2Cret_img%2Cw_1331%2Ch_800/https%3A//www.fltingenieriasas.com/wp-content/uploads/2022/03/plan-emergencias-.png',
    casoPractico: 'En una fábrica de alimentos, un trabajador sufrió una caída al no usar el calzado de seguridad. La empresa no contaba con un plan de emergencias, lo que retrasó la atención y generó caos entre los demás empleados. A raíz del incidente, la gerencia implementó un Sistema de Gestión en SST y diseñó un plan de emergencia, logrando reducir en un 70% los accidentes en el siguiente año.',
    video: 'https://www.youtube.com/watch?v=8myU_vlpvBQ',
    conclusiones: ["SST protege la vida y el trabajo.", "Los planes de emergencia son parte de la SST.", "Toda empresa debe tenerlos implementados."],
    },
    {
    id: 2,
    titulo: 'Lección 2 — Identificación de amenazas, evaluación de riesgos y medidas preventivas (aplicadas a emergencias)',
    objetivo: 'Objetivo: Aprender a identificar amenazas (naturales, tecnológicas, humanas), evaluar vulnerabilidades y priorizar controles preventivos que reduzcan la probabilidad e impacto de emergencias.',
    introduccion: 'Ninguna empresa está exenta de enfrentar situaciones que amenacen su seguridad. Los riesgos pueden provenir del interior —como fallas eléctricas, incendios o caídas— o del exterior —como desastres naturales o disturbios sociales—. La correcta identificación y evaluación de estas amenazas es el primer paso para la prevención. Al reconocerlos de forma sistemática, las organizaciones pueden implementar medidas que reduzcan su impacto y garanticen una reacción eficaz en caso de emergencia.',
    tituloA: 'Riesgos internos (eléctricos, incendios, caídas).',
    definicionA: 'Son los que se originan dentro de la empresa: fallas eléctricas, escapes de gas, incendios, mal almacenamiento de químicos, caídas o golpes. Estos pueden prevenirse con inspecciones periódicas, mantenimiento adecuado de equipos y capacitación del personal.',
    imagenA: 'https://media.istockphoto.com/id/1345309325/es/vector/conjunto-de-se%C3%B1ales-de-advertencia-de-peligro-precauci%C3%B3n-peligro-s%C3%ADmbolo-ilustraci%C3%B3n.jpg?s=612x612&w=0&k=20&c=bv-RFQytSKfEAt-hKU89m-9kc9SS0P1BoLKShXCK_v8=',
    tituloB: 'Riesgos externos (sismos, inundaciones, disturbios).',
    definicionB: 'Se relacionan con factores externos como desastres naturales (sismos, inundaciones, tormentas), situaciones sociales (disturbios, protestas) o accidentes en zonas cercanas (explosiones, derrames químicos). Aunque no siempre se pueden evitar, sí es posible mitigar sus efectos con planes adecuados de preparación.',
    imagenB: 'https://wiki.ead.pucv.cl/images/thumb/e/ea/PH_WIKI17.jpg/1000px-PH_WIKI17.jpg',
    casoPractico: 'En una oficina de una empresa de software, se descubrió que varias extensiones eléctricas estaban sobrecargadas, lo que generaba riesgo de incendio. El área de SST realizó una inspección, clasificó el riesgo como alto y ordenó la instalación de nuevos puntos eléctricos. Gracias a esta identificación temprana, se evitó un posible incendio que habría puesto en peligro la vida de 40 trabajadores.',
    video: 'https://www.youtube.com/watch?v=X2KGqjb7saY',
    conclusiones: ["Los riesgos pueden ser internos o externos.", "Identificarlos es el primer paso de un plan.", "La evaluación continua es fundamental."],
    },
    {
    id: 3,
    titulo: 'Lección 3 — Organización de la respuesta: brigada de emergencia, roles y formación',
    objetivo: 'Objetivo: Definir la estructura operativa para respuesta a emergencias: comité/brigada, funciones, formación y rotación de personal.',
    introduccion: 'En una situación de emergencia, cada segundo cuenta. La improvisación puede aumentar el caos y poner en peligro la vida de las personas. Por eso, es fundamental que toda organización cuente con brigadas de emergencia entrenadas y con roles claramente definidos. Estas brigadas se convierten en los primeros respondedores, capaces de coordinar evacuaciones, prestar primeros auxilios y apoyar en el control de incidentes, asegurando que la respuesta sea rápida, eficiente y ordenada.',
    tituloA: 'Tipos de brigadas (evacuación, primeros auxilios, incendios).',
    definicionA: 'Existen distintos tipos de brigadas como las brigada de evacuación (guía al personal hacia zonas seguras), las brigada de primeros auxilios (brinda atención inmediata a los heridos), las brigada contra incendios (utiliza extintores y controla conatos de incendio) y las brigada de comunicación (coordina la información entre brigadistas y personal externo)',
    imagenA: 'https://www.cpremergencias.com/wp-content/uploads/2020/06/DSCN8791.jpg',
    tituloB: 'Roles definidos (coordinador, líderes de piso, brigadistas).',
    definicionB: 'Un plan de emergencia requiere roles claros para evitar confusiones, estos roles estan compuestos por un coordinador general (dirige toda la operación), los líderes de piso o área (verifican que nadie quede atrás en evacuaciones) y los brigadistas (ejecutan tareas específicas de primeros auxilios, incendios o comunicación)',
    imagenB: 'https://www.ambientebogota.gov.co/documents/10184/645392/Organigrama-Brigada-SDA-2022.jpg/888a38e1-ebe2-4521-b282-0c0b36f50db6?t=1661551755176',
    casoPractico: 'En un centro comercial, un cliente se desmayó por un golpe de calor. La brigada de primeros auxilios actuó de inmediato: un brigadista inició RCP mientras otro coordinaba la llamada a emergencias. La rápida acción permitió estabilizar al paciente antes de la llegada de la ambulancia. Este hecho demostró la importancia de contar con brigadas entrenadas y roles definidos.',
    video: 'https://www.youtube.com/watch?v=Lucd_Z2c0o4',
    conclusiones: ["Una brigada organizada garantiza respuesta rápida.", "Roles claros evitan el caos.", "Entrenamiento constante es clave."],
    },
    {
    id: 4,
    titulo: 'Lección 4 — Plan de evacuación, señalización y realización de simulacros',
    objetivo: 'Objetivo: Diseñar rutas y puntos de encuentro, señalización adecuada y conocer la metodología para planificar, ejecutar y evaluar simulacros.',
    introduccion: 'La evacuación es uno de los procesos más críticos dentro de un plan de emergencia. No basta con tener rutas señalizadas; es necesario que las personas sepan exactamente qué hacer y hacia dónde dirigirse. Para lograrlo, los simulacros juegan un papel esencial: permiten poner a prueba los procedimientos, entrenar a los trabajadores y corregir fallas antes de que ocurra una emergencia real. De esta manera, se fortalece la confianza y se garantiza una evacuación más segura y eficaz.',
    tituloA: 'Señalización y rutas de evacuación',
    definicionA: 'Toda empresa debe contar con planos visibles de evacuación, salidas claramente señalizadas, puntos de encuentro y rutas libres de obstáculos. El personal debe conocer estas rutas y mantenerlas despejadas en todo momento.',
    imagenA: 'https://i.pinimg.com/originals/ff/88/74/ff8874667757c97860308489f3f826bf.jpg',
    tituloB: 'Simulacros como práctica preventiva',
    definicionB: 'Un simulacro permite ensayar el plan en condiciones controladas. Gracias a ellos se identifican fallas, se entrenan los brigadistas y se familiariza al personal con los procedimientos. La periodicidad recomendada es al menos dos veces al año.',
    imagenB: 'https://guayaquil.gob.ec/wp-content/uploads/2024/11/personas-cerca-empresas-participaron-activamente-simulacro-terremoto-guayaquil-2024-5.jpg',
    casoPractico: 'En una empresa textil de 300 trabajadores, se realizó un simulacro de incendio. En el primer intento, la evacuación tomó 12 minutos y varios empleados no sabían hacia dónde dirigirse. Tras ajustar la señalización y repetir el simulacro un mes después, el tiempo se redujo a 5 minutos, cumpliendo con los estándares internacionales. El ejercicio evidenció la necesidad de practicar y mejorar continuamente los procedimientos de evacuación.',
    video: 'https://www.youtube.com/watch?v=ZW5hd7Tz2wQ',
    conclusiones: ["Señalización y rutas claras son esenciales.", "Simulacros salvan vidas en la práctica real.", "Cada minuto cuenta en emergencias."],
    },
    {
    id: 5,
    titulo: 'Lección 5 — Atención inicial (primeros auxilios), comunicaciones y continuidad operacional.',
    objetivo: 'Objetivo: Conocer protocolos básicos de primeros auxilios en emergencias, comunicación interna/externa y medidas para asegurar la continuidad del servicio tras la emergencia.',
    introduccion: 'Los primeros minutos después de un accidente o una emergencia pueden marcar la diferencia entre salvar una vida o lamentar una pérdida. En este contexto, los primeros auxilios se convierten en una herramienta vital, ya que permiten estabilizar a la persona afectada hasta que llegue ayuda médica especializada. Contar con brigadistas capacitados y con botiquines bien equipados aumenta significativamente las posibilidades de una atención efectiva y oportuna dentro del lugar de trabajo.',
    tituloA: 'Uso del botiquín y materiales básicos',
    definicionA: 'El botiquín debe estar ubicado en un lugar visible y accesible. Debe contener elementos básicos como vendas, gasas, guantes, tijeras, termómetro, mascarillas y soluciones desinfectantes. Es responsabilidad de la brigada de primeros auxilios revisarlo periódicamente y reponer insumos vencidos.',
    imagenA: 'https://www.cedicol.com.co/wp-content/uploads/2023/10/BOTIQUIN-INSUMOS-TIPO-C-CON-BOLSO-AMBULANCIA.jpg',
    tituloB: 'Técnicas básicas (RCP, control de hemorragias).',
    definicionB: 'Algunas de las tecnicas uilizadas son el RCP (Reanimación Cardiopulmonar), el control de hemorragias con presión directa, la atención de quemaduras con agua limpia y vendaje y el traslado seguro de lesionados.',
    imagenB: 'https://image.ondacero.es/clipping/cmsimages01/2024/01/28/AA175CFB-8F9A-42F7-9566-E29D802DAA43/como-actuar-alguien-necesita-rcp-estos-son-tres-pasos-fundamentales_104.jpg?crop=3530,3530,x595,y0&width=1200&height=1200&optimize=low&format=webply',
    casoPractico: 'Durante un turno nocturno en una planta química, un trabajador sufrió una cortadura profunda en la mano. Un brigadista aplicó presión directa, elevó la extremidad y utilizó guantes para evitar infecciones. Posteriormente, el herido fue trasladado al hospital. Gracias a la atención inmediata, se evitó una hemorragia grave y el trabajador se recuperó sin complicaciones.',
    video: 'https://www.youtube.com/watch?v=lwCX1aq6tB4',
    conclusiones: ["Primeros auxilios estabilizan al herido hasta la ayuda médica.", "Todo trabajador debe recibir capacitación.", "Botiquines actualizados son vitales."],
    }
]
export default contenido;